# Generated by Django 4.2.13 on 2024-07-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EliteProductDeals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.CharField(default='https://www.amazon.ca/', max_length=200),
        ),
    ]
